// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: device.proto

package com.example.spring.grpc.grpc;

public interface BooleanReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.spring.grpc.BooleanReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool reply = 1;</code>
   */
  boolean getReply();
}
