// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: device.proto

package com.example.spring.grpc.grpc;

public interface ConditionsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.spring.grpc.ConditionsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
