// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: device.proto

package com.example.spring.grpc.grpc;

public final class DeviceFixProto {
  private DeviceFixProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_spring_grpc_ConditionsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_spring_grpc_ConditionsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_spring_grpc_DeviceFix_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_spring_grpc_DeviceFix_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_spring_grpc_BooleanReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_spring_grpc_BooleanReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_spring_grpc_ObjectReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_spring_grpc_ObjectReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014device.proto\022\027com.example.spring.grpc\"" +
      "\037\n\021ConditionsRequest\022\n\n\002id\030\001 \001(\t\"\222\001\n\tDev" +
      "iceFix\022\n\n\002id\030\001 \001(\t\022\021\n\tserialNum\030\002 \001(\t\022\017\n" +
      "\007userNum\030\003 \001(\t\022\016\n\006status\030\004 \001(\005\022\014\n\004type\030\005" +
      " \001(\005\022\017\n\007address\030\006 \001(\t\022\022\n\ncreatetime\030\007 \001(" +
      "\t\022\022\n\nupdatetime\030\010 \001(\t\"\035\n\014BooleanReply\022\r\n" +
      "\005reply\030\001 \001(\010\"\034\n\013ObjectReply\022\r\n\005reply\030\001 \001" +
      "(\0102\237\003\n\020DeviceFixService\022^\n\017insertDeviceF" +
      "ix\022\".com.example.spring.grpc.DeviceFix\032%" +
      ".com.example.spring.grpc.BooleanReply\"\000\022",
      "^\n\017updateDeviceFix\022\".com.example.spring." +
      "grpc.DeviceFix\032%.com.example.spring.grpc" +
      ".BooleanReply\"\000\022c\n\017searchDeviceFix\022*.com" +
      ".example.spring.grpc.ConditionsRequest\032\"" +
      ".com.example.spring.grpc.DeviceFix\"\000\022f\n\017" +
      "deleteDeviceFix\022*.com.example.spring.grp" +
      "c.ConditionsRequest\032%.com.example.spring" +
      ".grpc.BooleanReply\"\000B6\n\034com.example.spri" +
      "ng.grpc.grpcB\016DeviceFixProtoP\001\242\002\003HLWb\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_example_spring_grpc_ConditionsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_spring_grpc_ConditionsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_spring_grpc_ConditionsRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_example_spring_grpc_DeviceFix_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_spring_grpc_DeviceFix_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_spring_grpc_DeviceFix_descriptor,
        new java.lang.String[] { "Id", "SerialNum", "UserNum", "Status", "Type", "Address", "Createtime", "Updatetime", });
    internal_static_com_example_spring_grpc_BooleanReply_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_example_spring_grpc_BooleanReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_spring_grpc_BooleanReply_descriptor,
        new java.lang.String[] { "Reply", });
    internal_static_com_example_spring_grpc_ObjectReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_example_spring_grpc_ObjectReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_spring_grpc_ObjectReply_descriptor,
        new java.lang.String[] { "Reply", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
